### ISSUE TITLE
Fix `key` error in Home

### ISSUE THREAD

**Issue by Rahul5430** [PEC-CSS/ACM-PEC-Website#109]
<img width="461" alt="Screenshot 2022-10-29 at 6 36 41 PM" src="https://user-images.githubusercontent.com/67220225/198833191-4274633b-36fd-4dc6-aced-b0febda7c3f7.png">

**Comment by samsonlawal** [comment]
Can you assign this to me?

You also need to add keys to the BlogCard too, the warning will appear in the console after you fix the GroupCard.
