### ISSUE TITLE
Deploy this app on github pages

### ISSUE THREAD

**Issue by ultimatecoder2** [PEC-CSS/ACM-PEC-Website#3]
You need to deploy this app on github pages and also update the ci/cd workflow file, so that every new commit gets directly deployed

- To learn how to deploy a react app on github pages, you can follow this:
https://dev.to/yuribenjamin/how-to-deploy-react-app-in-github-pages-2a1f

- To update ci/cd workflow file for continuous deployment, you can follow this:
https://medium.com/front-end-weekly/ci-cd-with-github-actions-to-deploy-on-github-pages-73e225f8f131

- Don't forget to replace 'BrowserRouter' in src/app.js with 'HashRouter'. Otherwise react routing will not work properly on github pages.
You can refer this link: https://stackoverflow.com/questions/46016415/wheres-hashhistory-in-react-router-v4
An alternate way can be found here: https://github.com/facebook/create-react-app/issues/1765

**Comment by HarshDutt17** [comment]
Deployed on Github Pages
link: https://pec-css.github.io/ACM-PEC-Website/
