### ISSUE TITLE
Modify height of Div

### ISSUE THREAD

**Issue by HarshDutt17** [PEC-CSS/ACM-PEC-Website#39]
![image](https://user-images.githubusercontent.com/78022802/158308018-de22aeeb-df04-4a17-b561-0f7006cd0d86.png)
![image](https://user-images.githubusercontent.com/78022802/158308081-8b0a51f2-e044-4dbb-ae54-214a15637a4a.png)
![image](https://user-images.githubusercontent.com/78022802/158308101-96ad09e2-cb8f-4c03-a90a-72bd4f94dbc9.png)
Modify the heights of the first divs of About Us, and Projects to match Events div.
(Ensure the responsiveness of the divs throughout.)

**Comment by sri-rishi** [comment]
can you assign me this issue?

**Comment by samm-01** [comment]
Please assign this to me.

**Comment by Jhanvi528** [comment]
I would like to work on this issue

**Comment by HarshDutt17** [comment]
@sri-rishi I am assigning it to you

**Comment by sri-rishi** [comment]
thanks
