### ISSUE TITLE
Modify the image sizes on card

### ISSUE THREAD

**Issue by HarshDutt17** [PEC-CSS/ACM-PEC-Website#40]
![image](https://user-images.githubusercontent.com/78022802/158308238-7f832dab-f968-4859-b33b-ae707ee2feef.png)
Modify the image size and make it fluid.
(attach screenshot in your PRs of changes you have made)

**Comment by AshishRaikwar1290** [comment]
assign me this issue

**Comment by its-id** [comment]
Hi! Please assign me this issue.

**Comment by HarshDutt17** [comment]
@Indrakant-Dana Start working on it.
