### ISSUE TITLE
Modifying Projects Section

### ISSUE THREAD

**Issue by HarshDutt17** [PEC-CSS/ACM-PEC-Website#41]
![image](https://user-images.githubusercontent.com/78022802/158308482-cd6bdca4-83fc-4b73-9752-0bf85c714fca.png)
Hide the project cards below, and they should appear only when person clicks on *More* option of the carousel.

**Comment by darshikaguptaa** [comment]
Hey I am interested in working on this issue.
Please assign the issue to me

**Comment by Jhanvi528** [comment]
I would like to work on this issue

**Comment by HarshDutt17** [comment]
Assigning it to @darshikaguptaa , if you are willing to work respond with a comment.

**Comment by darshikaguptaa** [comment]
Yes sure

**Comment by darshikaguptaa** [comment]
@HarshDutt17 please checkout #83 , fixed the issue in there
