### ISSUE TITLE
Link Pic

### ISSUE THREAD

**Issue by HarshDutt17** [PEC-CSS/ACM-PEC-Website#44]
![image](https://user-images.githubusercontent.com/78022802/158309157-604a543b-c222-4898-8ec4-b851d617e77c.png)
Link profile photo from LinkedIn of Mr.Nishant Puri

**Comment by rakshitgondwal** [comment]
Hey @HarshDutt17 
I was trying to solve this issue but I am getting an error while running npm install. Can you help me figure it out?

**Comment by rakshitgondwal** [comment]
![Screenshot (185)](https://user-images.githubusercontent.com/98955085/181269127-8d6b5716-a437-4430-90a5-acc5611921cb.png)

**Comment by HarshDutt17** [comment]
try using
npm i -legacy-peer-deps

the issue is basically cause by react-reveal, since its an old library its searching for previous versions of react

**Comment by sri-rishi** [comment]
Hey @HarshDutt17, in this I have to add link of Nishant's linkedin profile,

**Comment by RSpec25** [comment]
secy photo is visible now @HarshDutt17. Close this issue.
