### ISSUE TITLE
Contact Us Footer | Details and Layout Edit

### ISSUE THREAD

**Issue by Sahilkumarrr13** [PEC-CSS/ACM-PEC-Website#60]
![image](https://user-images.githubusercontent.com/78020696/193601907-e4b6abb0-3ec2-45f9-a95a-58dbdb55f246.png)
Edit the Footer Section and Layout

**Comment by andreaevolo** [comment]
If I understood clearly, this footer layout should be replicated? If the answer is yes I would like to get assigned to this issue.

**Comment by darshikaguptaa** [comment]
Hey @Sahilkumarrr13 ,
I am interested in working on this issue.
Please assign this issue to me.

**Comment by Sahilkumarrr13** [comment]
> If I understood clearly, this footer layout should be replicated? If the answer is yes I would like to get assigned to this issue.

No, the footer has been already implemented on the web page and deployed, you're supposed to change the content and appearance of the footer in the page itself according to the content :)
If you got this, then i can assign you this

**Comment by Sahilkumarrr13** [comment]
> Hey @Sahilkumarrr13 ,
> I am interested in working on this issue.
> Please assign this issue to me.

Okay I'll assign you also this
