### ISSUE TITLE
Add Style to the subtitle 

### ISSUE THREAD

**Issue by AnkitaMalik22** [PEC-CSS/ACM-PEC-Website#68]
![Screenshot_20221005-173205~2.png](https://user-images.githubusercontent.com/80139836/194056076-f060250d-27c6-42da-a4d8-001966289411.png)
- increase the font size 
- change line height

I would love to work on this issue! Please assign me

**Comment by HarshDutt17** [comment]
Sure @AnkitaMalik22 , please add more description to issue.
