### ISSUE TITLE
Improve Blog CSS

### ISSUE THREAD

**Issue by Bibhavshah** [PEC-CSS/ACM-PEC-Website#69]
I believe with a little bit of Change in CSS the blog page can look more appealing.

![image](https://user-images.githubusercontent.com/78656387/194078826-652de39d-950d-413e-ab04-6b5e1e05701d.png)

And I feel I should start by correcting this simple yet important change that will make this part of the website look good. So, please confirm whether it is okay for you for me to work on this and assign me the issue if you feel good. #hacktoberfest.

**Comment by HarshDutt17** [comment]
sure @Bibhavshah go ahead.
