### ISSUE TITLE
Create a Matching Footer in the Site

### ISSUE THREAD

**Issue by vaibhava17** [PEC-CSS/ACM-PEC-Website#74]
Site Theme
![image](https://user-images.githubusercontent.com/65801959/194205626-c564b13e-cccb-45fd-81db-2eb092a0a6bc.png)

Current Footer
![image](https://user-images.githubusercontent.com/65801959/194205490-a8495085-cb42-47bc-931c-0a8fa16509f4.png)

I will create a matching footer for the site 
assign this task to me

**Comment by HarshDutt17** [comment]
sure @vaibhava17

**Comment by vaibhava17** [comment]
Open a PR #81
